//go:generate mockgen -package=discord -source=session.go -destination=session_mock.go
package discord

import (
	"image"
	"io"
	"time"

	"github.com/bwmarrin/discordgo"
)

type Session interface {
	Request(method, urlStr string, data interface{}, options ...discordgo.RequestOption) (response []byte, err error)
	RequestWithBucketID(method, urlStr string, data interface{}, bucketID string, options ...discordgo.RequestOption) (response []byte, err error)
	RequestWithLockedBucket(method, urlStr, contentType string, b []byte, bucket *discordgo.Bucket, sequence int, options ...discordgo.RequestOption) (response []byte, err error)
	User(userID string, options ...discordgo.RequestOption) (st *discordgo.User, err error)
	UserAvatar(userID string, options ...discordgo.RequestOption) (img image.Image, err error)
	UserAvatarDecode(u *discordgo.User, options ...discordgo.RequestOption) (img image.Image, err error)
	UserUpdate(username, avatar string, options ...discordgo.RequestOption) (st *discordgo.User, err error)
	UserConnections(options ...discordgo.RequestOption) (conn []*discordgo.UserConnection, err error)
	UserChannelCreate(recipientID string, options ...discordgo.RequestOption) (st *discordgo.Channel, err error)
	UserGuildMember(guildID string, options ...discordgo.RequestOption) (st *discordgo.Member, err error)
	UserGuilds(limit int, beforeID, afterID string, options ...discordgo.RequestOption) (st []*discordgo.UserGuild, err error)
	UserChannelPermissions(userID, channelID string, fetchOptions ...discordgo.RequestOption) (apermissions int64, err error)
	Guild(guildID string, options ...discordgo.RequestOption) (st *discordgo.Guild, err error)
	GuildWithCounts(guildID string, options ...discordgo.RequestOption) (st *discordgo.Guild, err error)
	GuildPreview(guildID string, options ...discordgo.RequestOption) (st *discordgo.GuildPreview, err error)
	GuildCreate(name string, options ...discordgo.RequestOption) (st *discordgo.Guild, err error)
	GuildEdit(guildID string, g *discordgo.GuildParams, options ...discordgo.RequestOption) (st *discordgo.Guild, err error)
	GuildDelete(guildID string, options ...discordgo.RequestOption) (st *discordgo.Guild, err error)
	GuildLeave(guildID string, options ...discordgo.RequestOption) (err error)
	GuildBans(guildID string, limit int, beforeID, afterID string, options ...discordgo.RequestOption) (st []*discordgo.GuildBan, err error)
	GuildBanCreate(guildID, userID string, days int, options ...discordgo.RequestOption) (err error)
	GuildBan(guildID, userID string, options ...discordgo.RequestOption) (st *discordgo.GuildBan, err error)
	GuildBanCreateWithReason(guildID, userID, reason string, days int, options ...discordgo.RequestOption) (err error)
	GuildBanDelete(guildID, userID string, options ...discordgo.RequestOption) (err error)
	GuildMembers(guildID string, after string, limit int, options ...discordgo.RequestOption) (st []*discordgo.Member, err error)
	GuildMembersSearch(guildID, query string, limit int, options ...discordgo.RequestOption) (st []*discordgo.Member, err error)
	GuildMember(guildID, userID string, options ...discordgo.RequestOption) (st *discordgo.Member, err error)
	GuildMemberAdd(guildID, userID string, data *discordgo.GuildMemberAddParams, options ...discordgo.RequestOption) (err error)
	GuildMemberDelete(guildID, userID string, options ...discordgo.RequestOption) (err error)
	GuildMemberDeleteWithReason(guildID, userID, reason string, options ...discordgo.RequestOption) (err error)
	GuildMemberEdit(guildID, userID string, data *discordgo.GuildMemberParams, options ...discordgo.RequestOption) (st *discordgo.Member, err error)
	GuildMemberEditComplex(guildID, userID string, data *discordgo.GuildMemberParams, options ...discordgo.RequestOption) (st *discordgo.Member, err error)
	GuildMemberMove(guildID string, userID string, channelID *string, options ...discordgo.RequestOption) (err error)
	GuildMemberNickname(guildID, userID, nickname string, options ...discordgo.RequestOption) (err error)
	GuildMemberMute(guildID string, userID string, mute bool, options ...discordgo.RequestOption) (err error)
	GuildMemberTimeout(guildID string, userID string, until *time.Time, options ...discordgo.RequestOption) (err error)
	GuildMemberDeafen(guildID string, userID string, deaf bool, options ...discordgo.RequestOption) (err error)
	GuildMemberRoleAdd(guildID, userID, roleID string, options ...discordgo.RequestOption) (err error)
	GuildMemberRoleRemove(guildID, userID, roleID string, options ...discordgo.RequestOption) (err error)
	GuildChannels(guildID string, options ...discordgo.RequestOption) (st []*discordgo.Channel, err error)
	GuildChannelCreateComplex(guildID string, data discordgo.GuildChannelCreateData, options ...discordgo.RequestOption) (st *discordgo.Channel, err error)
	GuildChannelCreate(guildID, name string, ctype discordgo.ChannelType, options ...discordgo.RequestOption) (st *discordgo.Channel, err error)
	GuildChannelsReorder(guildID string, channels []*discordgo.Channel, options ...discordgo.RequestOption) (err error)
	GuildInvites(guildID string, options ...discordgo.RequestOption) (st []*discordgo.Invite, err error)
	GuildRoles(guildID string, options ...discordgo.RequestOption) (st []*discordgo.Role, err error)
	GuildRoleCreate(guildID string, data *discordgo.RoleParams, options ...discordgo.RequestOption) (st *discordgo.Role, err error)
	GuildRoleEdit(guildID, roleID string, data *discordgo.RoleParams, options ...discordgo.RequestOption) (st *discordgo.Role, err error)
	GuildRoleReorder(guildID string, roles []*discordgo.Role, options ...discordgo.RequestOption) (st []*discordgo.Role, err error)
	GuildRoleDelete(guildID, roleID string, options ...discordgo.RequestOption) (err error)
	GuildPruneCount(guildID string, days uint32, options ...discordgo.RequestOption) (count uint32, err error)
	GuildPrune(guildID string, days uint32, options ...discordgo.RequestOption) (count uint32, err error)
	GuildIntegrations(guildID string, options ...discordgo.RequestOption) (st []*discordgo.Integration, err error)
	GuildIntegrationCreate(guildID, integrationType, integrationID string, options ...discordgo.RequestOption) (err error)
	GuildIntegrationEdit(guildID, integrationID string, expireBehavior, expireGracePeriod int, enableEmoticons bool, options ...discordgo.RequestOption) (err error)
	GuildIntegrationDelete(guildID, integrationID string, options ...discordgo.RequestOption) (err error)
	GuildIcon(guildID string, options ...discordgo.RequestOption) (img image.Image, err error)
	GuildSplash(guildID string, options ...discordgo.RequestOption) (img image.Image, err error)
	GuildEmbed(guildID string, options ...discordgo.RequestOption) (st *discordgo.GuildEmbed, err error)
	GuildEmbedEdit(guildID string, data *discordgo.GuildEmbed, options ...discordgo.RequestOption) (err error)
	GuildAuditLog(guildID, userID, beforeID string, actionType, limit int, options ...discordgo.RequestOption) (st *discordgo.GuildAuditLog, err error)
	GuildEmojis(guildID string, options ...discordgo.RequestOption) (emoji []*discordgo.Emoji, err error)
	GuildEmoji(guildID, emojiID string, options ...discordgo.RequestOption) (emoji *discordgo.Emoji, err error)
	GuildEmojiCreate(guildID string, data *discordgo.EmojiParams, options ...discordgo.RequestOption) (emoji *discordgo.Emoji, err error)
	GuildEmojiEdit(guildID, emojiID string, data *discordgo.EmojiParams, options ...discordgo.RequestOption) (emoji *discordgo.Emoji, err error)
	GuildEmojiDelete(guildID, emojiID string, options ...discordgo.RequestOption) (err error)
	GuildTemplate(templateCode string, options ...discordgo.RequestOption) (st *discordgo.GuildTemplate, err error)
	GuildCreateWithTemplate(templateCode, name, icon string, options ...discordgo.RequestOption) (st *discordgo.Guild, err error)
	GuildTemplates(guildID string, options ...discordgo.RequestOption) (st []*discordgo.GuildTemplate, err error)
	GuildTemplateCreate(guildID string, data *discordgo.GuildTemplateParams, options ...discordgo.RequestOption) (st *discordgo.GuildTemplate)
	GuildTemplateSync(guildID, templateCode string, options ...discordgo.RequestOption) (err error)
	GuildTemplateEdit(guildID, templateCode string, data *discordgo.GuildTemplateParams, options ...discordgo.RequestOption) (st *discordgo.GuildTemplate, err error)
	GuildTemplateDelete(guildID, templateCode string, options ...discordgo.RequestOption) (err error)
	Channel(channelID string, options ...discordgo.RequestOption) (st *discordgo.Channel, err error)
	ChannelEdit(channelID string, data *discordgo.ChannelEdit, options ...discordgo.RequestOption) (st *discordgo.Channel, err error)
	ChannelEditComplex(channelID string, data *discordgo.ChannelEdit, options ...discordgo.RequestOption) (st *discordgo.Channel, err error)
	ChannelDelete(channelID string, options ...discordgo.RequestOption) (st *discordgo.Channel, err error)
	ChannelTyping(channelID string, options ...discordgo.RequestOption) (err error)
	ChannelMessages(channelID string, limit int, beforeID, afterID, aroundID string, options ...discordgo.RequestOption) (st []*discordgo.Message, err error)
	ChannelMessage(channelID, messageID string, options ...discordgo.RequestOption) (st *discordgo.Message, err error)
	ChannelMessageSend(channelID string, content string, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelMessageSendComplex(channelID string, data *discordgo.MessageSend, options ...discordgo.RequestOption) (st *discordgo.Message, err error)
	ChannelMessageSendTTS(channelID string, content string, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelMessageSendEmbed(channelID string, embed *discordgo.MessageEmbed, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelMessageSendEmbeds(channelID string, embeds []*discordgo.MessageEmbed, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelMessageSendReply(channelID string, content string, reference *discordgo.MessageReference, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelMessageSendEmbedReply(channelID string, embed *discordgo.MessageEmbed, reference *discordgo.MessageReference, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelMessageSendEmbedsReply(channelID string, embeds []*discordgo.MessageEmbed, reference *discordgo.MessageReference, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelMessageEdit(channelID, messageID, content string, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelMessageEditComplex(m *discordgo.MessageEdit, options ...discordgo.RequestOption) (st *discordgo.Message, err error)
	ChannelMessageEditEmbed(channelID, messageID string, embed *discordgo.MessageEmbed, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelMessageEditEmbeds(channelID, messageID string, embeds []*discordgo.MessageEmbed, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelMessageDelete(channelID, messageID string, options ...discordgo.RequestOption) (err error)
	ChannelMessagesBulkDelete(channelID string, messages []string, options ...discordgo.RequestOption) (err error)
	ChannelMessagePin(channelID, messageID string, options ...discordgo.RequestOption) (err error)
	ChannelMessageUnpin(channelID, messageID string, options ...discordgo.RequestOption) (err error)
	ChannelMessagesPinned(channelID string, options ...discordgo.RequestOption) (st []*discordgo.Message, err error)
	ChannelFileSend(channelID, name string, r io.Reader, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelFileSendWithMessage(channelID, content string, name string, r io.Reader, options ...discordgo.RequestOption) (*discordgo.Message, error)
	ChannelInvites(channelID string, options ...discordgo.RequestOption) (st []*discordgo.Invite, err error)
	ChannelInviteCreate(channelID string, i discordgo.Invite, options ...discordgo.RequestOption) (st *discordgo.Invite, err error)
	ChannelPermissionSet(channelID, targetID string, targetType discordgo.PermissionOverwriteType, allow, deny int64, options ...discordgo.RequestOption) (err error)
	ChannelPermissionDelete(channelID, targetID string, options ...discordgo.RequestOption) (err error)
	ChannelMessageCrosspost(channelID, messageID string, options ...discordgo.RequestOption) (st *discordgo.Message, err error)
	ChannelNewsFollow(channelID, targetID string, options ...discordgo.RequestOption) (st *discordgo.ChannelFollow, err error)
	Invite(inviteID string, options ...discordgo.RequestOption) (st *discordgo.Invite, err error)
	InviteWithCounts(inviteID string, options ...discordgo.RequestOption) (st *discordgo.Invite, err error)
	InviteComplex(inviteID, guildScheduledEventID string, withCounts, withExpiration bool, options ...discordgo.RequestOption) (st *discordgo.Invite, err error)
	InviteDelete(inviteID string, options ...discordgo.RequestOption) (st *discordgo.Invite, err error)
	InviteAccept(inviteID string, options ...discordgo.RequestOption) (st *discordgo.Invite, err error)
	VoiceRegions(options ...discordgo.RequestOption) (st []*discordgo.VoiceRegion, err error)
	Gateway(options ...discordgo.RequestOption) (gateway string, err error)
	GatewayBot(options ...discordgo.RequestOption) (st *discordgo.GatewayBotResponse, err error)
	WebhookCreate(channelID, name, avatar string, options ...discordgo.RequestOption) (st *discordgo.Webhook, err error)
	ChannelWebhooks(channelID string, options ...discordgo.RequestOption) (st []*discordgo.Webhook, err error)
	GuildWebhooks(guildID string, options ...discordgo.RequestOption) (st []*discordgo.Webhook, err error)
	Webhook(webhookID string, options ...discordgo.RequestOption) (st *discordgo.Webhook, err error)
	WebhookWithToken(webhookID, token string, options ...discordgo.RequestOption) (st *discordgo.Webhook, err error)
	WebhookEdit(webhookID, name, avatar, channelID string, options ...discordgo.RequestOption) (st *discordgo.Role, err error)
	WebhookEditWithToken(webhookID, token, name, avatar string, options ...discordgo.RequestOption) (st *discordgo.Role, err error)
	WebhookDelete(webhookID string, options ...discordgo.RequestOption) (err error)
	WebhookDeleteWithToken(webhookID, token string, options ...discordgo.RequestOption) (st *discordgo.Webhook, err error)
	WebhookExecute(webhookID, token string, wait bool, data *discordgo.WebhookParams, options ...discordgo.RequestOption) (st *discordgo.Message, err error)
	WebhookThreadExecute(webhookID, token string, wait bool, threadID string, data *discordgo.WebhookParams, options ...discordgo.RequestOption) (st *discordgo.Message, err error)
	WebhookMessage(webhookID, token, messageID string, options ...discordgo.RequestOption) (message *discordgo.Message, err error)
	WebhookMessageEdit(webhookID, token, messageID string, data *discordgo.WebhookEdit, options ...discordgo.RequestOption) (st *discordgo.Message, err error)
	WebhookMessageDelete(webhookID, token, messageID string, options ...discordgo.RequestOption) (err error)
	MessageReactionAdd(channelID, messageID, emojiID string, options ...discordgo.RequestOption) error
	MessageReactionRemove(channelID, messageID, emojiID, userID string, options ...discordgo.RequestOption) error
	MessageReactionsRemoveAll(channelID, messageID string, options ...discordgo.RequestOption) error
	MessageReactionsRemoveEmoji(channelID, messageID, emojiID string, options ...discordgo.RequestOption) error
	MessageReactions(channelID, messageID, emojiID string, limit int, beforeID, afterID string, options ...discordgo.RequestOption) (st []*discordgo.User, err error)
	MessageThreadStartComplex(channelID, messageID string, data *discordgo.ThreadStart, options ...discordgo.RequestOption) (ch *discordgo.Channel, err error)
	MessageThreadStart(channelID, messageID string, name string, archiveDuration int, options ...discordgo.RequestOption) (ch *discordgo.Channel, err error)
	ThreadStartComplex(channelID string, data *discordgo.ThreadStart, options ...discordgo.RequestOption) (ch *discordgo.Channel, err error)
	ThreadStart(channelID, name string, typ discordgo.ChannelType, archiveDuration int, options ...discordgo.RequestOption) (ch *discordgo.Channel, err error)
	ForumThreadStartComplex(channelID string, threadData *discordgo.ThreadStart, messageData *discordgo.MessageSend, options ...discordgo.RequestOption) (th *discordgo.Channel, err error)
	ForumThreadStart(channelID, name string, archiveDuration int, content string, options ...discordgo.RequestOption) (th *discordgo.Channel, err error)
	ForumThreadStartEmbed(channelID, name string, archiveDuration int, embed *discordgo.MessageEmbed, options ...discordgo.RequestOption) (th *discordgo.Channel, err error)
	ForumThreadStartEmbeds(channelID, name string, archiveDuration int, embeds []*discordgo.MessageEmbed, options ...discordgo.RequestOption) (th *discordgo.Channel, err error)
	ThreadJoin(id string, options ...discordgo.RequestOption) error
	ThreadLeave(id string, options ...discordgo.RequestOption) error
	ThreadMemberAdd(threadID, memberID string, options ...discordgo.RequestOption) error
	ThreadMemberRemove(threadID, memberID string, options ...discordgo.RequestOption) error
	ThreadMember(threadID, memberID string, options ...discordgo.RequestOption) (member *discordgo.ThreadMember, err error)
	ThreadMembers(threadID string, options ...discordgo.RequestOption) (members []*discordgo.ThreadMember, err error)
	ThreadsActive(channelID string, options ...discordgo.RequestOption) (threads *discordgo.ThreadsList, err error)
	GuildThreadsActive(guildID string, options ...discordgo.RequestOption) (threads *discordgo.ThreadsList, err error)
	ThreadsArchived(channelID string, before *time.Time, limit int, options ...discordgo.RequestOption) (threads *discordgo.ThreadsList, err error)
	ThreadsPrivateArchived(channelID string, before *time.Time, limit int, options ...discordgo.RequestOption) (threads *discordgo.ThreadsList, err error)
	ThreadsPrivateJoinedArchived(channelID string, before *time.Time, limit int, options ...discordgo.RequestOption) (threads *discordgo.ThreadsList, err error)
	ApplicationCommandCreate(appID string, guildID string, cmd *discordgo.ApplicationCommand, options ...discordgo.RequestOption) (ccmd *discordgo.ApplicationCommand, err error)
	ApplicationCommandEdit(appID, guildID, cmdID string, cmd *discordgo.ApplicationCommand, options ...discordgo.RequestOption) (updated *discordgo.ApplicationCommand, err error)
	ApplicationCommandBulkOverwrite(appID string, guildID string, commands []*discordgo.ApplicationCommand, options ...discordgo.RequestOption) (createdCommands []*discordgo.ApplicationCommand, err error)
	ApplicationCommandDelete(appID, guildID, cmdID string, options ...discordgo.RequestOption) error
	ApplicationCommand(appID, guildID, cmdID string, options ...discordgo.RequestOption) (cmd *discordgo.ApplicationCommand, err error)
	ApplicationCommands(appID, guildID string, options ...discordgo.RequestOption) (cmd []*discordgo.ApplicationCommand, err error)
	GuildApplicationCommandsPermissions(appID, guildID string, options ...discordgo.RequestOption) (permissions []*discordgo.GuildApplicationCommandPermissions, err error)
	ApplicationCommandPermissions(appID, guildID, cmdID string, options ...discordgo.RequestOption) (permissions *discordgo.GuildApplicationCommandPermissions, err error)
	ApplicationCommandPermissionsEdit(appID, guildID, cmdID string, permissions *discordgo.ApplicationCommandPermissionsList, options ...discordgo.RequestOption) (err error)
	ApplicationCommandPermissionsBatchEdit(appID, guildID string, permissions []*discordgo.GuildApplicationCommandPermissions, options ...discordgo.RequestOption) (err error)
	InteractionRespond(interaction *discordgo.Interaction, resp *discordgo.InteractionResponse, options ...discordgo.RequestOption) error
	InteractionResponse(interaction *discordgo.Interaction, options ...discordgo.RequestOption) (*discordgo.Message, error)
	InteractionResponseEdit(interaction *discordgo.Interaction, newresp *discordgo.WebhookEdit, options ...discordgo.RequestOption) (*discordgo.Message, error)
	InteractionResponseDelete(interaction *discordgo.Interaction, options ...discordgo.RequestOption) error
	FollowupMessageCreate(interaction *discordgo.Interaction, wait bool, data *discordgo.WebhookParams, options ...discordgo.RequestOption) (*discordgo.Message, error)
	FollowupMessageEdit(interaction *discordgo.Interaction, messageID string, data *discordgo.WebhookEdit, options ...discordgo.RequestOption) (*discordgo.Message, error)
	FollowupMessageDelete(interaction *discordgo.Interaction, messageID string, options ...discordgo.RequestOption) error
	StageInstanceCreate(data *discordgo.StageInstanceParams, options ...discordgo.RequestOption) (si *discordgo.StageInstance, err error)
	StageInstance(channelID string, options ...discordgo.RequestOption) (si *discordgo.StageInstance, err error)
	StageInstanceEdit(channelID string, data *discordgo.StageInstanceParams, options ...discordgo.RequestOption) (si *discordgo.StageInstance, err error)
	StageInstanceDelete(channelID string, options ...discordgo.RequestOption) (err error)
	GuildScheduledEvents(guildID string, userCount bool, options ...discordgo.RequestOption) (st []*discordgo.GuildScheduledEvent, err error)
	GuildScheduledEvent(guildID, eventID string, userCount bool, options ...discordgo.RequestOption) (st *discordgo.GuildScheduledEvent, err error)
	GuildScheduledEventCreate(guildID string, event *discordgo.GuildScheduledEventParams, options ...discordgo.RequestOption) (st *discordgo.GuildScheduledEvent, err error)
	GuildScheduledEventEdit(guildID, eventID string, event *discordgo.GuildScheduledEventParams, options ...discordgo.RequestOption) (st *discordgo.GuildScheduledEvent, err error)
	GuildScheduledEventDelete(guildID, eventID string, options ...discordgo.RequestOption) (err error)
	GuildScheduledEventUsers(guildID, eventID string, limit int, withMember bool, beforeID, afterID string, options ...discordgo.RequestOption) (st []*discordgo.GuildScheduledEventUser, err error)
	AutoModerationRules(guildID string, options ...discordgo.RequestOption) (st []*discordgo.AutoModerationRule, err error)
	AutoModerationRule(guildID, ruleID string, options ...discordgo.RequestOption) (st *discordgo.AutoModerationRule, err error)
	AutoModerationRuleCreate(guildID string, rule *discordgo.AutoModerationRule, options ...discordgo.RequestOption) (st *discordgo.AutoModerationRule, err error)
	AutoModerationRuleEdit(guildID, ruleID string, rule *discordgo.AutoModerationRule, options ...discordgo.RequestOption) (st *discordgo.AutoModerationRule, err error)
	AutoModerationRuleDelete(guildID, ruleID string, options ...discordgo.RequestOption) (err error)
	ApplicationRoleConnectionMetadata(appID string) (st []*discordgo.ApplicationRoleConnectionMetadata, err error)
	ApplicationRoleConnectionMetadataUpdate(appID string, metadata []*discordgo.ApplicationRoleConnectionMetadata) (st []*discordgo.ApplicationRoleConnectionMetadata, err error)
	UserApplicationRoleConnection(appID string) (st *discordgo.ApplicationRoleConnection, err error)
	UserApplicationRoleConnectionUpdate(appID string, rconn *discordgo.ApplicationRoleConnection) (st *discordgo.ApplicationRoleConnection, err error)
	AddHandler(handler interface{}) func()
	AddHandlerOnce(handler interface{}) func()
	Open() error
	HeartbeatLatency() time.Duration
	UpdateGameStatus(idle int, name string) (err error)
	UpdateWatchStatus(idle int, name string) (err error)
	UpdateStreamingStatus(idle int, name string, url string) (err error)
	UpdateListeningStatus(name string) (err error)
	UpdateStatusComplex(usd discordgo.UpdateStatusData) (err error)
	RequestGuildMembers(guildID, query string, limit int, nonce string, presences bool) error
	RequestGuildMembersList(guildID string, userIDs []string, limit int, nonce string, presences bool) error
	RequestGuildMembersBatch(guildIDs []string, query string, limit int, nonce string, presences bool) (err error)
	RequestGuildMembersBatchList(guildIDs []string, userIDs []string, limit int, nonce string, presences bool) (err error)
	ChannelVoiceJoin(gID, cID string, mute, deaf bool) (voice *discordgo.VoiceConnection, err error)
	ChannelVoiceJoinManual(gID, cID string, mute, deaf bool) (err error)
	Close() error
	CloseWithCode(closeCode int) (err error)
}
